---
currency:
  USD: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    iso: USD
    rate: '21.50'
  EUR: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    iso: EUR
    rate: '23.59'
currency-test:
- !ruby/object:Currency
  attributes:
    iso: EUR
    rate: 23.59
- !ruby/object:Currency
  attributes:
    iso: USD
    rate: 21.5
